---
abstract: 'Check fork functionality.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Check-Fork
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Config: 0
  Exporter: 0
  Readonly: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Check-Fork/issues
  homepage: https://github.com/michal-josef-spacek/Check-Fork
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Check-Fork
version: '0.01'
